package tv.jellybeam.ui.cards

import uniffi.jellybeam_core.Card

/** A [Card] with every field defaulted to a harmless value -- tests override only what they need. */
fun testCard(
    id: String = "item-1",
    itemType: String = "Movie",
    name: String = "Item",
    primaryTag: String? = null,
    backdropTag: String? = null,
    thumbTag: String? = null,
    blurhash: String? = null,
    played: Boolean = false,
    positionTicks: Long = 0,
    runtimeTicks: Long? = null,
    unplayedCount: Long? = null,
    productionYear: Int? = null,
    indexNumber: Int? = null,
    premiereDate: String? = null,
    parentIndexNumber: Int? = null,
    seriesId: String? = null,
    seriesPrimaryTag: String? = null,
    parentBackdropItemId: String? = null,
    parentBackdropTag: String? = null,
    seriesName: String? = null,
    lastPlayedDate: String? = null,
    overview: String? = null,
    isVirtual: Boolean = false,
    libraryId: String? = null,
): Card = Card(
    id = id,
    itemType = itemType,
    name = name,
    primaryTag = primaryTag,
    backdropTag = backdropTag,
    thumbTag = thumbTag,
    blurhash = blurhash,
    played = played,
    positionTicks = positionTicks,
    runtimeTicks = runtimeTicks,
    unplayedCount = unplayedCount,
    productionYear = productionYear,
    indexNumber = indexNumber,
    premiereDate = premiereDate,
    parentIndexNumber = parentIndexNumber,
    seriesId = seriesId,
    seriesPrimaryTag = seriesPrimaryTag,
    parentBackdropItemId = parentBackdropItemId,
    parentBackdropTag = parentBackdropTag,
    seriesName = seriesName,
    lastPlayedDate = lastPlayedDate,
    overview = overview,
    isVirtual = isVirtual,
    libraryId = libraryId,
)
